### PR TITLE
Cleanup pom

### PR DESCRIPTION
**Pull request by mthmulders**

### CODE REVIEW

**Comment by simondel** [comment]
I noticed that this creates a jar file that is 6x smaller. Is that because of the plugin that you removed?

**Comment by mthmulders** [comment]
No, it is because I removed [Lombok](https://projectlombok.org/) from the the built artifact. Lombok is around 1.6 MB, so a relatively big boy. But due to its nature and what it does, it is only necessary at compile time, not at run time.

**Comment by simondel** [comment]
So in nodejs terms, you moved something from the `dependencies` to the `devDependencies`. That makes sense! Thanks for the explanation.

**Comment by nicojs** [comment]
@mthmulders nice find. Also: i'm feeling a little bit embarrassed :)

**Pull request merged**
